# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          curl https://qn.whyour.cn/version.yaml

      - name: Check Version
        run: |
          curl -sL https://qn.whyour.cn/version.yaml -o latest.yaml
          ls
          cat ./latest.yaml
          cur_version=$(cat latest.yaml | grep version | cut -d ':' -f 2 | tr -d ' "')
          echo "$cur_version"
