name: check

on:
  schedule:
    - cron: "0 0 * * 0" # 每周日的午夜RUN一次
  workflow_dispatch: # 手动触发事件

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v3

      - name: GET CURRENT VERSION FROM CACHE
        id: cache_version
        uses: actions/cache@v3
        with:
          path: .version
          # key: ${{ runner.OS }}-version-${{ github.sha }} # 使用commit SHA确保唯一性
          key: fixed-cache-key-for-version # 使用固定的缓存键

      - name: CHECK IF VERSION FILE EXISTS
        id: check_version_file
        run: |
          if [ -f ".version" ]; then
            echo "Version file found in cache."
            echo "::set-output name=version_file_found::true"
          else
            echo "Version file not found in cache."
            echo "::set-output name=version_file_found::false"
          fi

      - name: VERIFY CACHE
        if: steps.cache_version.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss for key: ${{ runner.OS }}-version-${{ github.sha }}"
          echo "Cache path: .version"
          echo "Cache hit: ${{ steps.cache_version.outputs.cache-hit }}"

      - name: GET CURRENT VERSION
        if: steps.check_version_file.outputs.version_file_found == 'false'
        run: |
          curl -sL https://qn.whyour.cn/version.yaml -o version.yaml
          current_version=$(cat version.yaml | grep version | cut -d ':' -f 2 | tr -d ' "')
          echo "current_version=$current_version" >>$GITHUB_ENV
          echo "$current_version" > .version # 将版本号写入文件以供缓存

      - name: COMPARE VERSIONS
        if: steps.check_version_file.outputs.version_file_found == 'true'
        run: |
          cached_version=$(cat .version)
          echo "Cached version: $cached_version"
          echo "Comparing with current version: ${{ env.current_version }}"
          # 这里可以添加比较逻辑和后续的RELEASE步骤
